### ISSUE TITLE
My lists of fake email addresses

### ISSUE THREAD

**Issue by kohkindachi** [maxd/fake_email_validator#1]
Hi thanks for your nice lists. Here's what I have which I see that it is NOT in your list:

emailz.ml
get-mail.ga
15qm-mail.red
20mail.in
20mail.it
abusemail.de
af.renraku.in
bossmail.de
boxtemp.com.br
bqgo6.anonbox.net
byom.de
disposableinbox.com
dodgemail.de
dodsi.com
ee1.pl
ee2.pl
email64.com
emailgo.de
fake-box.com
fastmail.com
fyii.de
getmails.eu
gfcom.com
grandmasmail.com
hiru-dea.com
hmamail.com
hushmail.com
imgof.com
inbox.si
ineec.net
instant-mail.de
junkmail.com
jupimail.com
kiois.com
lolfreak.net
mail1a.de
mail2world.com
maildu.de
maildx.com
mailed.ro
mailfs.com
mailhazard.com
mailsmagic.com
mallinator.com
mciek.com
migmail.pl
mindless.com
mohmal.com
mt2014.com
my10minutemail.com
mytemp.email
nincsmail.com
nincsmail.hu
nonspammer.de
one-time.email
openmailbox.org
opentrash.com
qisdo.com
qisoa.com
quickmail.nl
reconmail.com
re-gister.com
schafmail.de
secretemail.de
secure-mail.biz
secure-mail.cc
sinnlos-mail.de
slipry.net
slowslow.de
smoug.net
spambooger.com
spambpg.com
spoofmail.de
spybox.de
squizzy.de
streetwisemail.com
sute.jp
svk.jp
tempmail.de
tempmailer.com
tempsky.com
throam.com
tokenmail.de
trash-me.com
unlimit.com
vermutlich.net
vmail.me
voidbay.com
wegwerf-email.at
weg-werf-email.de
wem.com
writeme.com
yomail.info
yopmail.org
yoru-dea.com
you-spam.com
yyhmail.com
z1p.biz

**Comment by maxd** [comment]
Thank you a lot! :+1: I have verified and added most of these fake domains.
